serve:
	$(SHELL) start_server.sh
develop:
	$(SHELL) start_server_dev.sh
livereload:
	livereload --host 0.0.0.0 -t ./static
# pytest-watch:
# 	PYTHONPATH="src" pytest-watch

.PHONY: serve livereload develop
